name: Build & Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout nanolod
      uses: actions/checkout@v2
      with:
        path: nanolod/
    - name: Checkout nanomesh
      uses: actions/checkout@master
      with:
        name: nanolabo/nanomesh
        repository: nanolabo/nanomesh
        path: nanomesh/

    - name: List Files
      run: ls -R

    - name: List Fonts
      run: fc-list

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build Binaries
      run: dotnet build nanolod/Nanolod.sln

    - name: Install Documentation Tools
      run: sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
    - name: Build Documentation
      run: pandoc -V mainfont='Lato-Regular' nanolod/Manual/Manual.md -o nanolod/Package/Manual.pdf

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: nanolod/Package/