name: Build & Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout nanolod
      uses: actions/checkout@v2
      with:
        path: nanolod/
    - name: Checkout nanomesh
      uses: actions/checkout@master
      with:
        name: nanolabo/nanomesh
        repository: nanolabo/nanomesh
        path: nanomesh/
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: List Files
      run: ls -R
    - name: Build
      run: dotnet build nanolod/Nanolod.sln
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: nanolod/Package/
 
 
 
